print("welcome to the tip Calculator.")
total = input("What was the total bill? $")
int(total)
nPeople=input("How many people to split the bill? ")
int(nPeople)
tip=input("What % tip would ypu like to give?10,12 or 15? ")
int(tip)
percent = (int(tip)/100)*int(total)
int(percent)
pay = (int(total)+int(percent))/int(nPeople)
float(pay)
print("Each person should pay:",float(pay))
